config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web => "/sidekiq"

  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#index"

  resources :rooms do
    resources :messages
  end

  get "user/:id/chat" => "users#chat", as: :user_chat

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :user
  belongs_to :room

  validates :body, presence: true

  after_create_commit -> { broadcast_append_to(room, channel: ChatChannel, target: dom_id(room, :messages)) }
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates_uniqueness_of :user_id, scope: :room_id
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :participants, dependent: :destroy
  has_many :users, through: :participants
  has_many :messages, dependent: :destroy

  attr_accessor :recipient

  validates :name, presence: true, uniqueness: true, length: { minimum: 2 }

  after_create_commit { broadcast_if_public }

  scope :public_rooms, -> { where(is_private: false) }

  def full_title
    recipient && is_private ? recipient : name
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)

    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id )
    end

    single_room
  end

  private

  def broadcast_if_public
    broadcast_append_to "public_rooms", target: 'public_rooms', partial: 'rooms/room_link' unless self.is_private
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :all_except, ->(user) { where.not(id: user) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/chat_env.rb
module ChatEnv
  extend ActiveSupport::Concern

  included do
    def prepare_chat_env
      @users = User.all_except current_user
      @rooms = Room.public_rooms
      @new_room = Room.new
      @message = Message.new

      render 'rooms/index'
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def new; end

  def create
    room = Room.find params[:room_id]
    @new_message = current_user.messages.build(body: message_params[:body], room:)

    if @new_message.save
      respond_to do |format|
        format.turbo_stream

        format.html do
          flash[:notice] = 'Message was successfully sent'
          redirect_to room_path(@new_message.room)
        end
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  include ChatEnv

  def index
    prepare_chat_env
  end

  def create
    @new_room = Room.new room_params

    if @new_room.save
      respond_to do |format|
        flash.now[:notice] = 'Room was successfully created!'
        format.turbo_stream
        format.html { redirect_to rooms_path }
      end
    else
      flash[:alert] = 'Room was not successfully created!'
      redirect_to rooms_path
    end
  end

  def show
    @single_room = Room.find params[:id]
    prepare_chat_env
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  include ChatEnv

  def chat
    @user = User.find params[:id]
    room_name = make_room_name
    @single_room = Room.find_by_name(room_name) || Room.create_private_room([@user, current_user], room_name)
    @single_room.recipient = @user.email

    prepare_chat_env
  end

  private

  def make_room_name
    users = [@user, current_user].sort
    "private_#{users.map(&:id).join('_')}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.replace 'flash', partial: 'shared/flashes'
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbo Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <style>
      <%= ".msg-#{current_user&.id}"%> {
        flex-direction: row-reverse;
      }
    </style>
  </head>

  <body>
    <div class='flex flex-col'>
      <nav class="bg-blue-100 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
          <a href="https://flowbite.com/" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo">
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Turbo Test Chat</span>
          </a>
          <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
            <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
              <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
              </svg>
            </button>
          </div>
          <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
            <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
              <% if user_signed_in? %>
                <li>
                  <%= link_to current_user.email, '#', class: 'block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700'%>
                </li>
                <li>
                  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700'%>
                </li>
              <% else %>
                <li>
                  <%= link_to 'Log In', new_user_session_path, class: 'block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700' %>       
                </li>
                <li>
                  <%= link_to 'Sign In', new_user_registration_path, class: 'block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700' %>       
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class='mt-16 h-svh'>
        <%= turbo_frame_tag 'flash' do %>
          <%= render 'shared/flashes' %>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
 <div class="flex items-center mb-4 <%= "msg-#{message.user.id}"%>">
  <div class="flex-none flex flex-col items-center space-y-1 mr-4">
    <img class="rounded-full w-10 h-10"
      src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" />
    <a href="#" class="block text-xs hover:underline"><%= message.user.email %></a>
  </div>
  <div class="max-w-80 bg-indigo-400 text-white p-2 rounded-lg mb-2 relative">
    <p><%= message.body %></p>
  </div>
</div>

app/views/pages/index.html.erb
<div class='mx-auto max-w-fit'>
  <% if user_signed_in? %>
    <%= link_to rooms_path, class: 'mt-14 px-6 py-3.5 text-base font-medium text-white inline-flex items-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' do %>
      <svg class="w-4 h-4 text-white me-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16">
        <path d="m10.036 8.278 9.258-7.79A1.979 1.979 0 0 0 18 0H2A1.987 1.987 0 0 0 .641.541l9.395 7.737Z"/>
        <path d="M11.241 9.817c-.36.275-.801.425-1.255.427-.428 0-.845-.138-1.187-.395L0 2.6V14a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2.5l-8.759 7.317Z"/>
      </svg>
      Start Chatting!
    <% end %>
  <% else %>
    <h1 class="mt-14 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Please Log In to your accont to start chatting</h1>
  <% end %>
</div>

app/views/rooms/_room.html.erb
<div class="w-full max-w-screen-lg mx-auto h-96 flex flex-col border shadow-md bg-white">
  <div class='border-b'>
    <p class="mx-auto max-w-fit p-2"><%= room.full_title %></p>
  </div>

  <%= turbo_stream_from room %>

  <div id='chat-container' class="flex-1 px-4 py-4 overflow-y-auto">
    <%= turbo_frame_tag dom_id(room, :messages) do %>
      <%= render room.messages %>
    <% end %>
  </div>

  <%= form_with model: [@single_room, @message], data: { controller: 'chat-refresh', action: "turbo:submit-end->chat-refresh#clearInput", 'chat-refresh-room-value': room.name }, class: 'flex items-center border-t p-2' do |f| %>
    <%= f.text_field :body, required: true, placeholder: 'Aa', class: 'w-full rounded-full border border-gray-200' %>
    <%= f.button  class: 'inline-flex hover:bg-indigo-50 rounded-full p-2' do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
        </svg>
    <% end %>
  <% end %>
</div>

app/views/rooms/_room_link.html.erb
<li>
  <%= link_to room.name, room_path(room), class: 'font-medium text-blue-600 dark:text-blue-500 hover:underline'%>
</li>

app/views/rooms/create.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>

app/views/rooms/index.html.erb
<div class="flex h-full">
  <div class='grow-1 pt-10 shrink-0 flex flex-col px-4 bg-blue-100'>
    <h2 class="mb-2 text-lg font-semibold text-gray-900 dark:text-white">Users</h2>
    <ul class="max-h-32 overflow-y-auto space-y-1  text-gray-500 list-inside dark:text-gray-400">
      <% @users.each do |user| %>
        <li>
          <%= link_to user.email, user_chat_path(user), class: 'font-medium text-blue-600 dark:text-blue-500 hover:underline'%>
        </li>
      <% end %>
    </ul>

    <h2 class="mb-2 mt-6 text-lg font-semibold text-gray-900 dark:text-white">Rooms</h2>

    <%= form_with model: @new_room, class: 'max-w-screen-md mb-2', data: { controller: 'input-reset', action: "turbo:submit-end->input-reset#clear" } do |f| %>
      <%= f.text_field :name, required: true, class: 'inline-block bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' %>
      <%= f.submit 'Create', class: 'inline-block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
    <% end %>

    <ul id='public_rooms' class="max-h-32 overflow-y-auto space-y-1 text-gray-500 list-inside dark:text-gray-400">
      <%= turbo_stream_from 'public_rooms' %>

      <% @rooms.each do |room| %>
        <%= render partial: 'rooms/room_link', locals: { room: } %>
      <% end %>
    </ul>
  </div>

  <div class='grow pt-10'>
    <% if @single_room.present? %>
      <%= render 'rooms/room', room: @single_room %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice.present? %>
  <div class="flex max-w-fit mx-auto items-center p-4 my-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
    <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <div>
      <span class="font-medium"><%= notice %></span>
    </div>
  </div>
<% elsif alert.present? %>
  <div class="flex max-w-fit mx-auto items-center p-4 my-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
    <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <div>
      <span class="font-medium"><%= alert %></span>
    </div>
  </div>
<% end %>